version: '3.8'

# Create app from Dockerfile mapping port 5000
services:
  app:
    image: my-flask-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # Dependency id DB service that starts before
    depends_on:
      - db
    # Set environment variable for postgresql
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://flask:passwordhere@172.17.0.2/blog

  # Create db service mapping port 5432
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: blog 
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: passwordhere
    ports:
      - "5432:5432"
    # Create volume for data persistence
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

