name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run test on markdown
      run: |
        python markdown_validator.py

    - name: Build temporary docker image and create network
      run: |
        docker network create test_net
        docker-compose build

    - name: Run test for http responses
      run: |
        docker run --rm --name db --network test_net -d -p 5432:5432 -e POSTGRES_PASSWORD=passwordhere -e POSTGRES_USER=flask -e POSTGRES_DB=blog postgres:13
        docker run --rm --network test_net -e RUN_TESTS=true test

    - name: Delete temporary containers and network
      run: |
        docker stop db 
        docker network rm test_net

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Run deploy on AWS
      run: |
        chmod +x ../../deploy.sh
        ./../../deploy.sh